# Generated by Django 4.2.5 on 2023-09-30 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_choice_question_alter_question_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
