# Generated by Django 4.2.5 on 2023-09-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_is_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_multiple',
            field=models.BooleanField(default=True),
        ),
    ]
